# Generated by Django 3.2.9 on 2021-12-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreholdem', '0003_auto_20211206_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='game',
        ),
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.CharField(default='mesa', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='board',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreholdem.board'),
        ),
    ]
