# Generated by Django 3.2.9 on 2021-12-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreholdem', '0004_auto_20211210_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='mostradaEnMesa',
            field=models.BooleanField(default=False),
        ),
    ]
