# Generated by Django 3.2.9 on 2022-02-01 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreholdem', '0005_card_mostradaenmesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardOfBoard', to='coreholdem.board'),
        ),
        migrations.AlterField(
            model_name='card',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand', to='coreholdem.player'),
        ),
    ]
