# Generated by Django 3.2.9 on 2022-02-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreholdem', '0007_auto_20220214_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='show',
            field=models.IntegerField(default=3),
        ),
    ]
