# Generated by Django 3.2.9 on 2022-02-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreholdem', '0008_game_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='haApostado',
            field=models.BooleanField(default=False),
        ),
    ]
