# Generated by Django 3.2.9 on 2022-02-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreholdem', '0009_player_haapostado'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pasar',
            field=models.BooleanField(default=False),
        ),
    ]
