# Generated by Django 3.2.9 on 2022-02-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreholdem', '0010_player_pasar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='accion',
            field=models.BooleanField(default=False),
        ),
    ]
