# Generated by Django 3.2.9 on 2022-02-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreholdem', '0011_player_accion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='accion',
        ),
    ]
