# Generated by Django 3.2.9 on 2022-02-22 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreholdem', '0012_remove_player_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ganador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ganador', to='coreholdem.player'),
        ),
    ]
